category/urls.py
from django.urls import path

from category.views import CategoryCreateView, CategoryListView, CategoryUpdateView, CategoryDeleteView

app_name = 'category'

urlpatterns = [
    path('category-create/', CategoryCreateView.as_view(), name='category_create'),
    path('category-list/', CategoryListView.as_view(), name='category_list'),
    path('category-update/<int:pk>', CategoryUpdateView.as_view(), name='category_update'),
    path('category-delete/<int:pk>', CategoryDeleteView.as_view(), name='category_delete'),
]

django_first_app/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('category/', include('category.urls')),
    path('orders/', include('orders.urls')),
    path('products/', include('products.urls')),
    path('', LoginView.as_view(), name='login'),
    path('home/', include('home.urls')),
    path('users/', include('users.urls')),
    path('groups/', include('groups.urls')),
    path('permissions/', include('permissions.urls')),
]

groups/urls.py
from django.urls import path, include

from groups.views import GroupCreateView

app_name = 'groups'

urlpatterns = [
    path('groups-create/', GroupCreateView.as_view(), name='groups_create')
]

home/urls.py
from django.urls import path, include

from home.views import HomeTemplateView

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home_page')
]

orders/urls.py
from django.urls import path

from category.views import CategoryCreateView

app_name = 'orders'

urlpatterns = [

]

permissions/urls.py
from django.urls import path, include

from permissions.views import PermissionCreateView

app_name = 'permissions'

urlpatterns = [
    path('permission-create/', PermissionCreateView.as_view(), name='permission_create')
]

products/urls.py
from django.urls import path

from products.views import ProductCreateView, ProductListView, ProductUpdateView, ProductDeleteView

app_name = 'product'

urlpatterns = [
    path('product-create/', ProductCreateView.as_view(), name='product_create'),
    path('product-list/', ProductListView.as_view(), name='product_list'),
    path('product-update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('product-delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
]

users/urls.py
from django.urls import path, include

from users.views import UserCreateView

urlpatterns = [
    path('user-create/', UserCreateView.as_view(), name='create_user')
]

category/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

groups/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models

# Create your models here.

permissions/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    price = models.IntegerField(blank=False, null=False)
    category = models.ForeignKey('category.Category', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'Name of product is: {self.name}'

users/models.py
from django.contrib.auth.models import User
from django.db import models


class ExtendUser(User):
    phone = models.CharField(max_length=255, blank=True, null=True)
    group = models.ForeignKey('auth.Group', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from users.models import ExtendUser


class RegisterForm(UserCreationForm):
    class Meta:
        model = ExtendUser
        fields = ['first_name', 'last_name', 'email', 'username', 'group', 'phone']

category/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from category.form import CategoryForm
from category.models import Category


class CategoryCreateView(LoginRequiredMixin, CreateView):
    template_name = 'category/category_create.html'
    model = Category
    # fields = '__all__'
    success_url = reverse_lazy('category:category_list')
    form_class = CategoryForm


class CategoryListView(LoginRequiredMixin, ListView):
    template_name = 'category/category_list.html'
    model = Category
    context_object_name = 'all_categories'


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'category/category_update.html'
    model = Category
    # fields = ['name', 'description'] #'__all__'
    form_class = CategoryForm
    success_url = reverse_lazy('category:category_list')


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'category/category_delete.html'
    model = Category
    success_url = reverse_lazy('category:category_list')

groups/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.models import Group


class GroupCreateView(LoginRequiredMixin, CreateView):
    template_name = 'groups/groups_create.html'
    model = Group
    fields = '__all__'
    success_url = reverse_lazy('login')

@login_required #metoda se acceseaza logged in doar daca are decoratorul asta
def new_method():
    pass

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomeTemplateView(TemplateView):
    template_name = 'home.html'

orders/views.py
from django.shortcuts import render

# Create your views here.

permissions/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Permission
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView


class PermissionCreateView(LoginRequiredMixin, CreateView):
    template_name = 'permissions/permissions_create.html'
    model = Permission
    fields = '__all__'
    success_url = reverse_lazy('login')

products/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from products.models import Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    template_name = 'product/product_create.html'
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('product:product_list')
    # form_class =


class ProductListView(LoginRequiredMixin, ListView):
    template_name = 'product/product_list.html'
    model = Product
    context_object_name = 'all_products'


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'product/product_update.html'
    model = Product
    fields = '__all__'
    # form_class = ProductForm
    success_url = reverse_lazy('product:product_list')


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'product/product_delete.html'
    model = Product
    success_url = reverse_lazy('product:product_list')

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from users.forms import RegisterForm


class UserCreateView(CreateView):
    template_name = 'users/user_create.html'
    model = User
    success_url = reverse_lazy('login')
    form_class = RegisterForm

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

templates/category/category_create.html
{% extends 'base.html' %}

{% block titel %}
    Add new category
{% endblock %}

{% block content %}
    <a href='{% url 'category:category_list' %}'>List all categories</a>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
{#        {%  for field in form %}#}
{#            {{ field.as_p }}#}
{#        {% endfor %}#}
    <button type="submit">
        Save
    </button>
    </form>
{% endblock %}

templates/category/category_delete.html
{% extends 'base.html' %}

{% block title %}
    Category Deletion
{% endblock %}

{% block content %}
    <form method="post" action="">
        {%  csrf_token %}
        <p>Are you sure you want to delete this category?</p>
        <button type="submit">Delete</button>
    </form>
{% endblock %}

templates/category/category_list.html
{% extends 'base.html' %}

{% block title %}
    List of categories
{% endblock %}

{% block content %}
{#    {{ all_categories }}#}
    <a href="{% url 'category:category_create' %}"> Add new category</a>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Actions</th>
            </tr>
        </thead>
    <tbody>
    {% for category in all_categories %}
        <tr>
            <th>{{ category.id }}</th>
            <th>{{ category.name }}</th>
            <th>{{ category.description }}</th>
            <th>
                <a href="{% url 'category:category_update' category.id%}">Update category</a>
                <a href="{% url 'category:category_delete' category.id%}">Delete category</a>
            </th>
        </tr>
{#        <p>{{ category }}</p>#}
{#        <p>{{ category.name }}</p>#}
{#        <p>{{ category.description }}</p>#}
{#        <a href="{% url 'category:category_update' category.id%}">Update category</a>#}
    {% endfor %}
    </tbody>
    </table>
    <a href="{% url 'logout' %}">Logout</a>
    <a href="{% url 'home_page' %}">Home</a>
{% endblock %}

templates/category/category_update.html
{% extends 'base.html' %}

{% block title %}
    Update Category
{% endblock %}

{% block content %}
    <a href="{% url 'category:category_list' %}">List categories</a>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>

    </form>
{% endblock %}

templates/groups/groups_create.html
{% extends 'base.html' %}

{% block title %}
    Group Creation
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create group</button>
    </form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}
    Stores home
{% endblock %}

{% block content %}
    <h4>Salut {{ request.user.first_name }}</h4>
    <nav>
        {% if perms.category.view_category %}
            <a href="{% url 'category:category_list' %}">All Categories</a>
            <br><a href="{% url 'product:product_list' %}">Products</a>
        {% endif %}
{#        {{ request.user.extenduser.group }}#}
        {% if request.user.extenduser.group == 'Administrator' %}
            <br><a href="{% url 'groups:groups_create' %}">Create Group</a>
        {% endif %}
        <br><a href="{% url 'groups:groups_create' %}">Create Group</a>
        <br><a href="{% url 'permissions:permission_create' %}">Create Permissions</a>
    </nav>

{% endblock %}

templates/permissions/permissions_create.html
{% extends 'base.html' %}

{% block title %}
    Permission Creation
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create permission</button>
    </form>
{% endblock %}

templates/product/product_create.html
{% extends 'base.html' %}

{% block title %}
    Add new product
{% endblock %}

{% block content %}
    <a href="{% url 'product:product_list' %}">List all products</a>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">
        Save
    </button>
    </form>
{% endblock %}

templates/product/product_delete.html
{% extends 'base.html' %}

{% block title %}
    Product Deletion
{% endblock %}

{% block content %}
    <form method="post" action="">
        {%  csrf_token %}
        <p>Are you sure you want to delete this product?</p>
        <button type="submit">Delete</button>
    </form>
{% endblock %}

templates/product/product_list.html
{% extends 'base.html' %}

{% block title %}
    List of products
{% endblock %}

{% block content %}
{#    {{ all_categories }}#}
    <a href="{% url 'product:product_create' %}"> Add new product</a>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Price</th>
                <th>Category</th>
                <th>Description</th>
            </tr>
        </thead>
    <tbody>
    {% for product in all_products %}
        <tr>
            <th>{{ product.id }}</th>
            <th>{{ product.name }}</th>
            <th>{{ product.price }}</th>
            <th>{{ product.category }}</th>
            <th>{{ product.description }}</th>
            <th>
                <a href="{% url 'product:product_update' product.id%}">Update product</a>
                </br><a href="{% url 'product:product_delete' product.id%}">Delete product</a>
            </th>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    <a href="{% url 'logout' %}">Logout</a>
    <a href="{% url 'home_page' %}">Home</a>
{% endblock %}

templates/product/product_update.html
{% extends 'base.html' %}

{% block title %}
    Update Product
{% endblock %}

{% block content %}
    <a href="{% url 'product:product_list' %}"> List products</a>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
{% endblock %}

templates/users/user_create.html
{% extends 'base.html' %}

{% block title %}
    Create New User
{% endblock %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create user</button>
    </form>
    <a href="{% url 'login' %}">Back</a>
{% endblock %}